name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Do a release build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: hexerator-win64-build
        path: target/release/hexerator.exe